import { Select } from '../../components/Select'
import { useState } from 'react'
import { Avatar, Badge, Icon, SectionTitle } from './components'
import { players, type Screen } from './demoData'
import { demoGames, demoPolls, initialPollTemplates } from './productDemoData'
import { BackButton, Empty, MiniStats, Notice, PageHeading, Search, money } from './screenComponents'
import { EventTemplatesScreen, PollTemplatesScreen } from './TemplateScreens'
import { DebtsScreen } from './DebtsScreen'

export function ProductScreens({ screen, visited, navigate }: { screen: Screen; visited: Screen[]; navigate: (value: Screen) => void }) {
  const [templates, setTemplates] = useState(initialPollTemplates)
  // Keep visited screens mounted so in-memory edits survive navigation within a concept.
  const screens = {
    profile: <ProfileScreen navigate={navigate}/>,
    templates: <PollTemplatesScreen templates={templates} onChange={setTemplates}/>,
    event_templates: <EventTemplatesScreen templates={templates}/>,
    games: <GamesScreen/>,
    polls: <PollsScreen/>,
    billing: <DebtsScreen/>,
  }
  return <>{(Object.keys(screens) as (keyof typeof screens)[]).filter(id => visited.includes(id)).map(id => <div key={id} className="dl-product-screen" hidden={screen !== id}>{screens[id]}</div>)}</>
}

function ProfileScreen({ navigate }: { navigate: (value: Screen) => void }) {
  const [roles, setRoles] = useState(['Организатор', 'Игрок', 'Игрок', 'Капитан', 'Игрок', 'Тренер'])
  const [member, setMember] = useState(1)
  const [role, setRole] = useState('Капитан')
  const [notice, setNotice] = useState('')
  const [history, setHistory] = useState('Все встречи')
  const trainings = [{ title: 'Вечерний волейбол', date: '14 сентября', time: '19:00–21:00', future: true, price: 600 }, { title: 'Субботняя тренировка', date: '12 сентября', time: '11:00–13:00', future: false, price: 750 }, { title: 'Играем в среду', date: '9 сентября', time: '20:00–22:00', future: false, price: 600 }, { title: 'Вечерний волейбол', date: '7 сентября', time: '19:00–21:00', future: false, price: 600 }]
  return <><PageHeading eyebrow="МОЁ МЕСТО В КОМАНДЕ" title="Мой профиль" description="Ваши встречи, роль в клубе и история участия."/>
    <div className="dl-profile-layout"><section className="dl-panel dl-profile-card"><div className="dl-profile-cover"><Icon name="ball" size={110}/><span>ОРБИТА / СЕЗОН 2026</span></div><Avatar large/><h2>Алексей Морозов</h2><p>@alex_morozov</p><Badge>Организатор</Badge><div className="dl-profile-facts"><div><span>На площадке</span><strong>Связующий</strong></div><div><span>С нами с</span><strong>Марта 2025</strong></div><div><span>Уровень игры</span><strong>8.4 <small>/ 10</small></strong></div></div><button className="dl-button dl-secondary dl-wide" onClick={() => navigate('members')}>Игроки моей команды<Icon name="arrow" size={16}/></button></section>
    <div><MiniStats items={[{ label: 'Тренировок', value: '36', note: 'За всё время', icon: 'calendar' }, { label: 'Посещаемость', value: '92%', note: 'За последние 3 месяца', icon: 'ball' }, { label: 'Задолженность', value: '0 ₽', note: 'Все взносы оплачены', icon: 'wallet' }]}/><section className="dl-panel"><SectionTitle title="Мои встречи"/><div className="dl-filter-tabs">{['Все встречи', 'Предстоящие', 'Завершённые'].map(t => <button key={t} className={history === t ? 'dl-filter-active' : ''} onClick={() => setHistory(t)}>{t}</button>)}</div><div className="dl-history-list">{trainings.filter(t => history === 'Все встречи' || (history === 'Предстоящие' ? t.future : !t.future)).map((t, i) => <div className="dl-history-row" key={t.date}><span className="dl-history-icon"><Icon name={t.future ? 'calendar' : 'check'} size={19}/></span><div><strong>{t.title}</strong><small>{t.date} · {t.time}</small></div><span className="dl-history-amount"><strong>{money(t.price)}</strong><small>{t.future ? 'Предварительный взнос' : 'Оплачено'}</small></span>{t.future ? <button className="dl-icon-button" aria-label="Перейти к предстоящим событиям" onClick={() => navigate('events')}><Icon name="arrow" size={18}/></button> : <span className="dl-history-complete" aria-label={`Встреча ${i + 1} завершена`}><Icon name="check" size={17}/></span>}</div>)}</div></section></div></div>
    <section className="dl-panel dl-roles-panel"><SectionTitle title="Роли в клубе"/><p className="dl-section-description">Доверьте тренеру и капитану часть забот о команде.</p><div className="dl-role-members">{[3, 5].map(i => <div key={i}><Avatar index={i}/><span><strong>{players[i].name}</strong><small>{roles[i]}</small></span></div>)}</div><form className="dl-role-form dl-form dl-product-form" onSubmit={e => { e.preventDefault(); setRoles(values => values.map((v, i) => i === member ? role : v)); setNotice(`${players[member].name}: назначена роль «${role}»`) }}><label>Участник<Select value={member} onChange={e => setMember(Number(e.target.value))}>{players.slice(1).map((p, i) => <option value={i + 1} key={p.name}>{p.name} · {roles[i + 1]}</option>)}</Select></label><label>Роль<Select value={role} onChange={e => setRole(e.target.value)}>{['Капитан', 'Тренер', 'Игрок'].map(r => <option key={r}>{r}</option>)}</Select></label><button className="dl-button dl-primary" type="submit">Назначить роль<Icon name="check" size={16}/></button></form><Notice>{notice}</Notice></section>
  </>
}

function GamesScreen() {
  const [filter, setFilter] = useState('Все события')
  const [expanded, setExpanded] = useState<number | null>(1)
  const filtered = demoGames.filter(g => filter === 'Все события' || g.event === filter)
  return <><PageHeading eyebrow="КАЖДАЯ ПАРТИЯ — СВОЯ ИСТОРИЯ" title="Игры и результаты" description="Счёт на табло. Люди за каждым очком."/><div className="dl-results-hero"><div><p className="dl-eyebrow">ПОСЛЕДНЯЯ ВСТРЕЧА · 12 СЕНТЯБРЯ</p><h2>Суббота, которую<br/>хочется повторить.</h2><p>3 сохранённые партии · Спортцентр «Старт»</p></div><div className="dl-results-score"><span>Орбита<strong>2</strong></span><i>:</i><span>Импульс<strong>1</strong></span><small>ПОБЕДЫ В ПАРТИЯХ</small></div></div>
    <div className="dl-section-title"><h2>Журнал партий</h2><span className="dl-demo-note">{filtered.length} записей</span></div><div className="dl-filters"><Select aria-label="Фильтр игр по событию" value={filter} onChange={e => setFilter(e.target.value)}>{['Все события', 'Субботняя тренировка', 'Играем в среду'].map(f => <option key={f}>{f}</option>)}</Select></div>
    <div className="dl-games-list">{filtered.map(g => <article className={`dl-panel dl-game-card${expanded === g.id ? ' dl-game-open' : ''}`} key={g.id}><div className="dl-game-meta"><span>{g.date} · {g.event}</span><small>ПАРТИЯ {String(g.ordinal).padStart(2, '0')}</small></div><button className="dl-game-result" aria-label={`Составы: ${g.date}, партия ${g.ordinal}`} aria-expanded={expanded === g.id} onClick={() => setExpanded(expanded === g.id ? null : g.id)}><span className="dl-game-team"><i>A</i><strong>{g.teamA}</strong></span><span className="dl-game-score"><strong className={g.a > g.b ? 'dl-winner' : ''}>{g.a}</strong><i>:</i><strong className={g.b > g.a ? 'dl-winner' : ''}>{g.b}</strong></span><span className="dl-game-team dl-game-team-b"><strong>{g.teamB}</strong><i>B</i></span><span className="dl-roster-toggle">Составы<Icon name={expanded === g.id ? 'close' : 'down'} size={16}/></span></button>{expanded === g.id && <div className="dl-game-rosters">{[0, 1].map(team => <div key={team}><h3>{team === 0 ? g.teamA : g.teamB}<small>3 демопрофиля</small></h3>{players.filter((_, i) => i % 2 === team).map(p => <div className="dl-team-person" key={p.name}><Avatar index={players.indexOf(p)}/><span><strong>{p.name}</strong><small>{p.role}</small></span><b>{p.skill.toFixed(1)}</b></div>)}</div>)}</div>}</article>)}</div>
  </>
}

function PollsScreen() {
  const [selectedID, setSelectedID] = useState<number | null>(null)
  const [filter, setFilter] = useState('Все голосования')
  const [query, setQuery] = useState('')
  const [voteFilter, setVoteFilter] = useState('Все ответы')
  const selected = demoPolls.find(p => p.id === selectedID)
  if (selected) {
    const total = selected.counts.reduce((sum, count) => sum + count, 0)
    const counted = selected.counts[0] + selected.counts[1] * 2
    return <><BackButton onClick={() => setSelectedID(null)}>Все голосования</BackButton><PageHeading eyebrow={`ГОЛОСОВАНИЕ №${selected.id} · ${selected.date.toUpperCase()}`} title={selected.name} description={`Опубликовано ${selected.published} · ${selected.template}`} action={<Badge muted={!selected.active}>{selected.active ? 'Идёт голосование' : 'Завершено'}</Badge>}/><div className="dl-poll-detail-layout"><section className="dl-panel dl-poll-results"><p className="dl-eyebrow">ВОПРОС КОМАНДЕ</p><h2>{selected.question}</h2>{selected.options.map((o, i) => <div className="dl-vote-bar" key={o}><div><strong>{o}</strong><span>{selected.counts[i]} <small>· {Math.round(selected.counts[i] / total * 100)}%</small></span></div><div className={`dl-progress${i === 2 ? ' dl-progress-muted' : ''}`}><span style={{ width: `${selected.counts[i] / total * 100}%` }}/></div></div>)}<div className="dl-poll-totals"><span><strong>{total}</strong>ответов</span><span><strong>{counted}</strong>участников в составе</span></div></section><aside className="dl-poll-context"><Icon name="users" size={28}/><h2>Команда собирается</h2><p>Ответ «Буду с другом» учитывает двух участников. Отказ не добавляет человека в состав.</p><span className="dl-answer-chips"><span className="dl-counted-chip"><Icon name="check" size={13}/>Учтено {counted} мест</span></span></aside></div><SectionTitle title="Ответы участников"/><div className="dl-filters"><Search placeholder="Найти участника голосования" value={query} onChange={setQuery}/><Select aria-label="Фильтр ответов" value={voteFilter} onChange={e => setVoteFilter(e.target.value)}>{['Все ответы', 'В составе', 'Не участвуют'].map(f => <option key={f}>{f}</option>)}</Select></div><div className="dl-panel dl-voters-list">{players.filter((p, i) => p.name.toLowerCase().includes(query.toLowerCase()) && (voteFilter === 'Все ответы' || (voteFilter === 'В составе' ? i !== 4 : i === 4))).map(p => { const i = players.indexOf(p); return <div className="dl-voter-row" key={p.name}><Avatar index={i}/><span><strong>{p.name}</strong><small>{i === 5 ? 'Добавлен организатором' : 'Голос из Telegram'}</small></span><span className={`dl-vote-choice${i === 4 ? ' dl-vote-no' : ''}`}>{selected.options[i === 4 ? 2 : i === 2 ? 1 : 0]}</span><small>{12 + i}:0{i}</small></div> })}{!players.some((p, i) => p.name.toLowerCase().includes(query.toLowerCase()) && (voteFilter === 'Все ответы' || (voteFilter === 'В составе' ? i !== 4 : i === 4))) && <Empty>Нет участников с такими условиями поиска.</Empty>}</div><p className="dl-demo-note">Показаны 6 демопрофилей из {total} ответивших.</p></>
  }
  const filtered = demoPolls.filter(p => filter === 'Все голосования' || (filter === 'Активные' ? p.active : !p.active))
  return <><PageHeading eyebrow="КТО СЕГОДНЯ С НАМИ" title="Голосования" description="Все опубликованные вопросы, ответы и готовность команды."/><MiniStats items={[{ label: 'Открыта запись', value: '2', note: 'На предстоящие события', icon: 'poll' }, { label: 'Участников в составе', value: '28', note: 'На понедельник и среду', icon: 'users' }, { label: 'Завершено', value: '1', note: 'Субботняя тренировка', icon: 'check' }]}/><div className="dl-filter-tabs">{['Все голосования', 'Активные', 'Завершённые'].map(f => <button key={f} className={filter === f ? 'dl-filter-active' : ''} onClick={() => setFilter(f)}>{f}</button>)}</div><div className="dl-template-grid">{filtered.map(p => <article className="dl-panel dl-poll-card" key={p.id}><div className="dl-card-top"><span className="dl-eyebrow">{p.date.toUpperCase()}</span><Badge muted={!p.active}>{p.active ? 'Активно' : 'Завершено'}</Badge></div><h2>{p.question}</h2><p>{p.name}</p>{p.options.map((o, i) => <div className="dl-poll-mini-result" key={o}><span>{o}</span><strong>{p.counts[i]}</strong><i style={{ width: `${p.counts[i] / p.counts.reduce((a, b) => a + b, 0) * 100}%` }}/></div>)}<div className="dl-card-bottom"><small>{p.counts.reduce((a, b) => a + b, 0)} ответов</small><button className="dl-text-button" onClick={() => { setSelectedID(p.id); setQuery(''); setVoteFilter('Все ответы') }}>Ответы участников<Icon name="arrow" size={16}/></button></div></article>)}</div></>
}
